# https://taskfile.dev

version: '3'

vars:
  HOST: "127.0.0.1"
  PORT: "8000"

tasks:
  default:
    desc: "Start the PV forecast server"
    cmds:
      - uv run uvicorn app:app --host {{.HOST}} --port {{.PORT}} --reload
    silent: false

  dev:
    desc: "Start the server in development mode with auto-reload"
    cmds:
      - uv run uvicorn app:app --host {{.HOST}} --port {{.PORT}} --reload --log-level debug
    silent: false

  install:
    desc: "Install dependencies using uv"
    cmds:
      - uv sync
    silent: false
